### ISSUE TITLE
Did anyone tried to build it using CMake?

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [headcrab-garage/Xash3DEx#29]
Because I didn't

**Comment by CrusoeDaWolf** [comment]
I can test it out. Which branch do you want me to clone and compile?

**Comment by Sh1ft0x0EF** [comment]
melon-dev, please
Thanks!

**Comment by CrusoeDaWolf** [comment]
Ok. Anything I need to know for compiling with CMake? CMake arguments and things like that?

**Comment by CrusoeDaWolf** [comment]
Ignore above. I cloned the repo using:
`git clone https://github.com/projectogs/Xash3DEx -b melon-dev`

Then, I did:
`git submodule init; git submodule update`

Afterwards:
`mkdir -p build; cd build; cmake ../`

CMake complained about MPEG_LIBRARY set to not found, so I installed mpg123 and this time did:
`cmake -DMPEG_LIBRARY=/usr/bin/mpg123 ../`

It worked, but when I ran `make`, I got an error saying something along the lines of "Hello! Linux isn't supported yet! Come back later!"

At least we are getting somewhere. c:

**Comment by Sh1ft0x0EF** [comment]
So you're on Linux?
Interesting...
There's is no mpg123 libs for Linux placed in thirdparty
But it looks like these CMakeLists are applicable to build the engine on Linux so it just need to apply the usage of SDL2 or something else maybe?
I've already done some code base fixes for it to be more platform-independent
There are still places here and there which using the Win32 API directly and should be fixed
But the engine is mostly ready to implement the cross-platform support for it

**Comment by CrusoeDaWolf** [comment]
I am on Arch Linux and I enabled the multilib repo then installed 32-bit mpg (lib32-mpg123 in the Arch repos).

**Comment by Sh1ft0x0EF** [comment]
Well
I'm aimed on finally making this engine cross-platform
The question is about which framework to use
SDL2 is already used by SDLash so I'm a unsure if XashEx should use it too

**Comment by CrusoeDaWolf** [comment]
What other frameworks are available?

**Comment by Sh1ft0x0EF** [comment]
https://en.wikipedia.org/wiki/ClanLib
https://en.wikipedia.org/wiki/Allegro_(software)
https://en.wikipedia.org/wiki/Simple_and_Fast_Multimedia_Library

**Comment by CrusoeDaWolf** [comment]
Personally, I'd want to go with the smallest framework, but it is up to you. Perhaps have a poll or something to decide which framework to use?

**Comment by Sh1ft0x0EF** [comment]
Nobody cares
There's is a bug that crashes the engine when you open the server-list currently but nobody still didn't reported about it despite that it's there since February

**Comment by CrusoeDaWolf** [comment]
Fair enough!

**Comment by Sh1ft0x0EF** [comment]
I think that it also would be good to check out the GitHub and search for some interesting frameforks
SFML is out in it's current state - it directly exports it's classes so in order to use it you need the precompiled libs specially for your version of the compiler (So in VS case it has a set of precompiled binaries for each of 10-15 versions)
ClanLib looks interesting and I thinks it would be used if there's no any variants

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf What do you mean by "smallest"?

**Comment by CrusoeDaWolf** [comment]
Most lightweight/with the least amount of dependencies.

**Comment by Sh1ft0x0EF** [comment]
Legacy Quake sources...? How's about that?

**Comment by Sh1ft0x0EF** [comment]
I'm thinking about splitting the engine subsystems into their own dlls like for ogs-ac96 (and Source)

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf It came out that the precompiled hdr was moved from "engine/system" to the "engine/" folder but the sources weren't respectively updated so there is no chance you would be able to compile the engine anyway

**Comment by CrusoeDaWolf** [comment]
RIP Linux support for the moment then.

**Comment by Sh1ft0x0EF** [comment]
I've already fixed most of the include entries already
I'm currently rewriting the engine to support the subsystems as dlls
For the initial Linux support they will be implemented as null-impl dlls
I'm using the same approach as in Q2 for it's renderer module - a cvar for module name and functions to load the module itself + potentially hot-swapping support
I'll apply the split for the network/input/sound modules for now but maybe I'll also split all the rendering code from the engine and put it inside it's own dll with preserving the ability to implement it inside the client dll
With this approach it would be possible to apply any module implementation using any framework (and it still will be possible to link them all inside)

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , could you try to build it? It will fail to compile the gl_vidnt.c cause it still uses the WinAPI funcs but other parts should compile fine now (except for subsystem modules, they're still wip). I need the build log from you

**Comment by CrusoeDaWolf** [comment]
I will build when I get back home.

**Comment by CrusoeDaWolf** [comment]
`In file included from /home/ssardiko/Xash3DEx/launcher/main.cpp:31:0:
/home/ssardiko/Xash3DEx/common/platform.h:44:20: fatal error: direct.h: No such file or directory
 #include <direct.h>
                    ^
compilation terminated.
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
Sorry, my bad
Could you try again using the latest commit?
I think you should be able to successfully build both the launcher and menu modules then (I hope)

**Comment by CrusoeDaWolf** [comment]
`In file included from /home/ssardiko/Xash3DEx/launcher/main.cpp:29:0:
/home/ssardiko/Xash3DEx/common/platform.h:46:16: fatal error: io.h: No su$
 #include <io.h>
                ^
compilation terminated.
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CM$
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/a$
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
crap

**Comment by Sh1ft0x0EF** [comment]
Could you comment out the error line in platform.h (#include <io.h>) for now?

**Comment by CrusoeDaWolf** [comment]
This is what I get now:

` 
/home/ssardiko/Xash3DEx/launcher/main.cpp:32:32: fatal error: common/commontypes.h: No such file or directory
 #include "common/commontypes.h"
                                ^
compilation terminated.
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
Did you init the hlsdk submodule?

**Comment by CrusoeDaWolf** [comment]
Whoops. Forgot to do that. :P

` [  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
In file included from /home/ssardiko/Xash3DEx/launcher/main.cpp:30:0:
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void* Sys_LoadLibrary(const char*)’:
/home/ssardiko/Xash3DEx/common/utils.h:45:19: error: ‘void* Sys_LoadLibrary(const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static tLibHandle Sys_LoadLibrary(const char *name)
                   ^~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h:38:12: note: previous declaration of ‘void* Sys_LoadLibrary(const char*)’
 tLibHandle Sys_LoadLibrary(const char *name);
            ^~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void* Sys_LoadLibrary(const char*)’:
/home/ssardiko/Xash3DEx/common/utils.h:52:15: error: ‘RTLD_NOW’ was not declared in this scope
  dlopen(name, RTLD_NOW);
               ^~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h:52:23: error: ‘dlopen’ was not declared in this scope
  dlopen(name, RTLD_NOW);
                       ^
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void* Sys_GetExportFunc(tLibHandle, const char*)’:
/home/ssardiko/Xash3DEx/common/utils.h:60:14: error: ‘void* Sys_GetExportFunc(tLibHandle, const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void *Sys_GetExportFunc(tLibHandle hLib, const char *name)
              ^~~~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h:41:7: note: previous declaration of ‘void* Sys_GetExportFunc(tLibHandle, const char*)’
 void *Sys_GetExportFunc(tLibHandle hLib, const char *name);
       ^~~~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void* Sys_GetExportFunc(tLibHandle, const char*)’:
/home/ssardiko/Xash3DEx/common/utils.h:67:18: error: ‘dlsym’ was not declared in this scope
  dlsym(hLib, name);
                  ^
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void Sys_FreeLibrary(tLibHandle)’:
/home/ssardiko/Xash3DEx/common/utils.h:75:13: error: ‘void Sys_FreeLibrary(tLibHandle)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void Sys_FreeLibrary(tLibHandle hLib)
             ^~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h:39:6: note: previous declaration of ‘void Sys_FreeLibrary(tLibHandle)’
 void Sys_FreeLibrary(tLibHandle hLib);
      ^~~~~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/utils.h: In function ‘void Sys_FreeLibrary(tLibHandle)’:
/home/ssardiko/Xash3DEx/common/utils.h:80:14: error: ‘dlclose’ was not declared in this scope
  dlclose(hLib);
              ^
In file included from /home/ssardiko/Xash3DEx/launcher/main.cpp:31:0:
/home/ssardiko/Xash3DEx/common/crtlib.h: At global scope:
/home/ssardiko/Xash3DEx/common/crtlib.h:60:1: error: ‘qboolean’ does not name a type
 qboolean Q_isdigit(const char *str);
 ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:70:1: error: ‘qboolean’ does not name a type
 qboolean Q_stricmpext(const char *s1, const char *s2);
 ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘void Q_strnupr(const char*, char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:84:13: error: ‘void Q_strnupr(const char*, char*, size_t)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void Q_strnupr(const char *in, char *out, size_t size_out)
             ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:50:6: note: previous declaration of ‘void Q_strnupr(const char*, char*, size_t)’
 void Q_strnupr(const char *in, char *out, size_t size_out);
      ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘void Q_strnlwr(const char*, char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:100:13: error: ‘void Q_strnlwr(const char*, char*, size_t)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void Q_strnlwr(const char *in, char *out, size_t size_out)
             ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:52:6: note: previous declaration of ‘void Q_strnlwr(const char*, char*, size_t)’
 void Q_strnlwr(const char *in, char *out, size_t size_out);
      ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_strlen(const char*)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:116:12: error: ‘int Q_strlen(const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_strlen(const char *string)
            ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:53:5: note: previous declaration of ‘int Q_strlen(const char*)’
 int Q_strlen(const char *string);
     ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char Q_toupper(char)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:136:13: error: ‘char Q_toupper(char)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char Q_toupper(const char in)
             ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:54:6: note: previous declaration of ‘char Q_toupper(char)’
 char Q_toupper(const char in);
      ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char Q_tolower(char)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:148:13: error: ‘char Q_tolower(char)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char Q_tolower(const char in)
             ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:55:6: note: previous declaration of ‘char Q_tolower(char)’
 char Q_tolower(const char in);
      ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘size_t Q_strncat(char*, const char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:160:15: error: ‘size_t Q_strncat(char*, const char*, size_t)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static size_t Q_strncat(char *dst, const char *src, size_t size)
               ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:57:8: note: previous declaration of ‘size_t Q_strncat(char*, const char*, size_t)’
 size_t Q_strncat(char *dst, const char *src, size_t siz);
        ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘size_t Q_strncpy(char*, const char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:194:15: error: ‘size_t Q_strncpy(char*, const char*, size_t)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static size_t Q_strncpy(char *dst, const char *src, size_t size)
               ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:59:8: note: previous declaration of ‘size_t Q_strncpy(char*, const char*, size_t)’
 size_t Q_strncpy(char *dst, const char *src, size_t siz);
        ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: At global scope:
/home/ssardiko/Xash3DEx/common/crtlib.h:224:8: error: ‘qboolean’ does not name a type
 static qboolean Q_isdigit(const char *str)
        ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_atoi(const char*)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:236:12: error: ‘int Q_atoi(const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_atoi(const char *str)
            ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:61:5: note: previous declaration of ‘int Q_atoi(const char*)’
 int Q_atoi(const char *str);
     ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘float Q_atof(const char*)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:292:14: error: ‘float Q_atof(const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static float Q_atof(const char *str)
              ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:62:7: note: previous declaration of ‘float Q_atof(const char*)’
 float Q_atof(const char *str);
       ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘void Q_atov(float*, const char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:368:13: error: ‘void Q_atov(float*, const char*, size_t)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void Q_atov(float *vec, const char *str, size_t siz)
             ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:63:6: note: previous declaration of ‘void Q_atov(float*, const char*, size_t)’
 void Q_atov(float *vec, const char *str, size_t siz);
      ^~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘void Q_atov(float*, const char*, size_t)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:375:24: error: ‘vec_t’ was not declared in this scope
  memset(vec, 0, sizeof(vec_t) * siz);
                        ^~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_strchr(const char*, char)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:393:14: error: ‘char* Q_strchr(const char*, char)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *Q_strchr(const char *s, char c)
              ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:64:7: note: previous declaration of ‘char* Q_strchr(const char*, char)’
 char *Q_strchr(const char *s, char c);
       ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_strrchr(const char*, char)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:405:14: error: ‘char* Q_strrchr(const char*, char)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *Q_strrchr(const char *s, char c)
              ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:65:7: note: previous declaration of ‘char* Q_strrchr(const char*, char)’
 char *Q_strrchr(const char *s, char c);
       ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_strnicmp(const char*, const char*, int)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:419:12: error: ‘int Q_strnicmp(const char*, const char*, int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_strnicmp(const char *s1, const char *s2, int n)
            ^~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:67:5: note: previous declaration of ‘int Q_strnicmp(const char*, const char*, int)’
 int Q_strnicmp(const char *s1, const char *s2, int n);
     ^~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_strncmp(const char*, const char*, int)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:458:12: error: ‘int Q_strncmp(const char*, const char*, int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_strncmp(const char *s1, const char *s2, int n)
            ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:69:5: note: previous declaration of ‘int Q_strncmp(const char*, const char*, int)’
 int Q_strncmp(const char *s1, const char *s2, int n);
     ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: At global scope:
/home/ssardiko/Xash3DEx/common/crtlib.h:491:8: error: ‘qboolean’ does not name a type
 static qboolean Q_starcmp(const char *pattern, const char *text)
        ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:515:8: error: ‘qboolean’ does not name a type
 static qboolean Q_stricmpext(const char *pattern, const char *text)
        ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘const char* Q_timestamp(int)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:541:20: error: ‘const char* Q_timestamp(int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static const char *Q_timestamp(int format)
                    ^~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:71:13: note: previous declaration of ‘const char* Q_timestamp(int)’
 const char *Q_timestamp(int format);
             ^~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_stristr(const char*, const char*)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:585:14: error: ‘char* Q_stristr(const char*, const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *Q_stristr(const char *string, const char *string2)
              ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:72:7: note: previous declaration of ‘char* Q_stristr(const char*, const char*)’
 char *Q_stristr(const char *string, const char *string2);
       ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_strstr(const char*, const char*)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:612:14: error: ‘char* Q_strstr(const char*, const char*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *Q_strstr(const char *string, const char *string2)
              ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:73:7: note: previous declaration of ‘char* Q_strstr(const char*, const char*)’
 char *Q_strstr(const char *string, const char *string2);
       ^~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_vsnprintf(char*, size_t, const char*, va_list)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:639:12: error: ‘int Q_vsnprintf(char*, size_t, const char*, va_list)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_vsnprintf(char *buffer, size_t buffersize, const char *format, va_list args)
            ^~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:75:5: note: previous declaration of ‘int Q_vsnprintf(char*, size_t, const char*, va_list)’
 int Q_vsnprintf(char *buffer, size_t buffersize, const char *format, va_list args);
     ^~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_vsnprintf(char*, size_t, const char*, va_list)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:643:54: error: ‘_vsnprintf’ was not declared in this scope
  result = _vsnprintf(buffer, buffersize, format, args);
                                                      ^
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_snprintf(char*, size_t, const char*, ...)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:653:12: error: ‘int Q_snprintf(char*, size_t, const char*, ...)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_snprintf(char *buffer, size_t buffersize, const char *format, ...)
            ^~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:76:5: note: previous declaration of ‘int Q_snprintf(char*, size_t, const char*, ...)’
 int Q_snprintf(char *buffer, size_t buffersize, const char *format, ...);
     ^~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_sprintf(char*, const char*, ...)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:665:12: error: ‘int Q_sprintf(char*, const char*, ...)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int Q_sprintf(char *buffer, const char *format, ...)
            ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:77:5: note: previous declaration of ‘int Q_sprintf(char*, const char*, ...)’
 int Q_sprintf(char *buffer, const char *format, ...);
     ^~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_pretifymem(float, int)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:677:14: error: ‘char* Q_pretifymem(float, int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *Q_pretifymem(float value, int digitsafterdecimal)
              ^~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h:79:7: note: previous declaration of ‘char* Q_pretifymem(float, int)’
 char *Q_pretifymem(float value, int digitsafterdecimal);
       ^~~~~~~~~~~~
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* Q_pretifymem(float, int)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:705:48: error: ‘max’ was not declared in this scope
  digitsafterdecimal = max(digitsafterdecimal, 0);
                                                ^
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘char* va(const char*, ...)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:761:14: error: ‘char* va(const char*, ...)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char *va(const char *format, ...)
              ^~
/home/ssardiko/Xash3DEx/common/crtlib.h:80:7: note: previous declaration of ‘char* va(const char*, ...)’
 char *va(const char *format, ...);
       ^~
/home/ssardiko/Xash3DEx/launcher/main.cpp: In function ‘void Sys_ChangeGame(const char*)’:
/home/ssardiko/Xash3DEx/launcher/main.cpp:103:23: error: ‘TRUE’ was not declared in this scope
  Host_Main(szGameDir, TRUE, (Host_Shutdown != NULL) ? Sys_ChangeGame : NULL);
                       ^~~~
/home/ssardiko/Xash3DEx/launcher/main.cpp: In function ‘int main(int, char**)’:
/home/ssardiko/Xash3DEx/launcher/main.cpp:114:30: error: ‘FALSE’ was not declared in this scope
  return Host_Main(GAME_PATH, FALSE, (Host_Shutdown != NULL) ? Sys_ChangeGame : NULL);
                              ^~~~~
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2 `

**Comment by Sh1ft0x0EF** [comment]
Ouch
Give me a sec

**Comment by CrusoeDaWolf** [comment]
It is fine! Take your time! c:

**Comment by Sh1ft0x0EF** [comment]
* Please add the following line in platform.h inside the __ linux __ section:
`#include <dlfcn.h>`
* Add add the -fpermissive flag for now
* Also you need to fix the include order in launcher/main.cpp; you need to raise the
`#include "common/commontypes.h"`
two lines higher (place it below the platform.h)
* And add the following inside the main.cpp:
```cpp
#define TRUE 1
#define FALSE 0
```

**Comment by CrusoeDaWolf** [comment]
` [  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
In file included from /home/ssardiko/Xash3DEx/launcher/main.cpp:32:0:
/home/ssardiko/Xash3DEx/common/crtlib.h: In function ‘int Q_vsnprintf(char*, size_t, const char*, va_list)’:
/home/ssardiko/Xash3DEx/common/crtlib.h:643:54: error: ‘_vsnprintf’ was not declared in this scope
  result = _vsnprintf(buffer, buffersize, format, args);
                                                      ^
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
`

Getting closer!

**Comment by Sh1ft0x0EF** [comment]
common/crtlib.h:643
Remove the '_' symbol from the _vsnprintf and that should be good

**Comment by CrusoeDaWolf** [comment]
> [  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
[  1%] Linking CXX executable ../../bin/cmake/launcher
CMakeFiles/launcher.dir/main.cpp.o: In function `Sys_LoadLibrary(char const*)':
main.cpp:(.text+0xf): undefined reference to `dlopen'
CMakeFiles/launcher.dir/main.cpp.o: In function `Sys_GetExportFunc(void*, char const*)':
main.cpp:(.text+0x2e): undefined reference to `dlsym'
CMakeFiles/launcher.dir/main.cpp.o: In function `Sys_FreeLibrary(void*)':
main.cpp:(.text+0x4a): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:95: ../bin/cmake/launcher] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Sh1ft0x0EF** [comment]
Well, at least launcher is compilable now
Need to fix the linking stage now

**Comment by Sh1ft0x0EF** [comment]
Add "-ldl" to your linker options please

**Comment by CrusoeDaWolf** [comment]
`[  1%] Linking CXX executable ../../bin/cmake/launcher
[  1%] Built target launcher
Scanning dependencies of target menu
[  2%] Building CXX object mainui/CMakeFiles/menu.dir/basemenu.cpp.o
In file included from /home/ssardiko/Xash3DEx/mainui/basemenu.cpp:24:0:
/home/ssardiko/Xash3DEx/mainui/extdll.h:26:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
make[2]: *** [mainui/CMakeFiles/menu.dir/build.make:63: mainui/CMakeFiles/menu.dir/basemenu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: mainui/CMakeFiles/menu.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by Sh1ft0x0EF** [comment]
mainui/extdll.h:26
Replace the
`#include <windows.h>`
with
`#include "platform.h"`

**Comment by Sh1ft0x0EF** [comment]
mainui/udll_int.cpp
Please remove or put in conditional compilation this func:

```cpp
#ifdef _WIN32 // add this
// main DLL entry point
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
	return TRUE;
};
#endif // and this
```

**Comment by CrusoeDaWolf** [comment]
[https://pastebin.com/Z2iMLxzh](url)

**Comment by Sh1ft0x0EF** [comment]
Alright, I'll fix these errors and post a commit a bit later

**Comment by Sh1ft0x0EF** [comment]
One more thing
Could you try to build the engine module too?
Just open the root CMakeLists file and comment out the
`add_subdirectory(mainui)`
line and post the log of the engine module compilation
Thx

**Comment by CrusoeDaWolf** [comment]
[https://pastebin.com/W6jafLdn](url)

**Comment by Sh1ft0x0EF** [comment]
Well
I've made it compilable by MinGW 6.2 on Windows (Still unbuildable because of unresolved)
I hope you can compile it too
You don't need to add -fpermissive and -ldl flags now (I'm not sure about -fpermissive but we'll see)

**Comment by CrusoeDaWolf** [comment]
`[  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
In file included from /home/ssardiko/Xash3DEx/common/platform.h:57:0,
                 from /home/ssardiko/Xash3DEx/launcher/main.cpp:29:
/home/ssardiko/Xash3DEx/common/platform/platform_linux.h:33:3: error: #error "You shouldn't include this file directly! Use platform.h file instead!"
  #error "You shouldn't include this file directly! Use platform.h file instead!"
   ^~~~~
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

This is what I get now

**Comment by Sh1ft0x0EF** [comment]
Sorry, i've missed that
Open the common/platform/platform_linux.h file and edit the 32 line
You need to change it to:
```cpp
#ifndef XASH_PLATFORM_SELECTED

**Comment by CrusoeDaWolf** [comment]
I'm sorry but I do not understand. Line 32 is already `#ifndef XASH_PLATFORM_SELECTED`

**Comment by Sh1ft0x0EF** [comment]
My initial comment was wrong and I already fixed it
You need this line:
`#ifndef XASHEX_PLATFORM_SELECTED`
I've fixed it when I was compiling for Win but Linux and others remained untouched

**Comment by CrusoeDaWolf** [comment]
Like I said, line 32 already has `#ifndef XASHEX_PLATFORM_SELECTED`

**Comment by Sh1ft0x0EF** [comment]
xashex or xash? it should be xashex and it should be compilable with it

**Comment by CrusoeDaWolf** [comment]
XashEx

> /*
> platform_linux.h - linux (UNIX) platform types/definitions
> Copyright (C) 2017 Xash3D Devs

> GNU 2 License blah blah blah

> #ifndef XASH_PLATFORM_LINUX_H
> #define XASH_PLATFORM_LINUX_H

> #ifndef XASH_PLATFORM_SELECTED
> 	#error "You shouldn't include this file directly! Use platform.h file instead!"
> #endif

> #include <unistd.h>
> #include <ctype.h>
> #include <limits.h>
> #include <sys/time.h>
> #include <sys/ioctl.h>
> #include <signal.h>
> #include <dlfcn.h>

> enum
> {
> 	FALSE = 0,
> 	TRUE
> };

> #endif // XASH_PLATFORM_LINUX_H

**Comment by Sh1ft0x0EF** [comment]
Yep
`#ifndef XASH_PLATFORM_SELECTED`
should be replaced with
`#ifndef XASHEX_PLATFORM_SELECTED`

**Comment by CrusoeDaWolf** [comment]
[https://pastebin.com/8jD9nfnk](url)

**Comment by Sh1ft0x0EF** [comment]
Thx
Could you also try to build the engine?

**Comment by CrusoeDaWolf** [comment]
`Scanning dependencies of target xash
[  0%] Building C object CMakeFiles/xash.dir/CMakeFiles/3.8.0/CompilerIdC/CMakeCCompilerId.o
[  1%] Building C object CMakeFiles/xash.dir/CMakeFiles/feature_tests.o
[  2%] Building C object CMakeFiles/xash.dir/client/cl_cmds.o
In file included from /home/ssardiko/Xash3DEx/engine/client/cl_cmds.c:29:0:
/home/ssardiko/Xash3DEx/engine/precompiled.h:36:22: fatal error: platform.h: No such file or directory
 #include "platform.h"
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/xash.dir/build.make:111: CMakeFiles/xash.dir/client/cl_cmds.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/xash.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
Hm, weird

**Comment by Sh1ft0x0EF** [comment]
Oh, are you trying to build it directly from engine/CMakeLists?

**Comment by CrusoeDaWolf** [comment]
Yes, I am

**Comment by Sh1ft0x0EF** [comment]
You shouldn't do that
All shared config info are placed inside the root CMakeLists (and include directories too)

**Comment by CrusoeDaWolf** [comment]
How should I build the engine then? make?

**Comment by Sh1ft0x0EF** [comment]
Just comment out the mainui subdirectory to skip it

**Comment by CrusoeDaWolf** [comment]
https://pastebin.com/0Usg3Q4Y

**Comment by Sh1ft0x0EF** [comment]
Thank you
I'll fix these errors and apply the initial unix impl for subsystems
Can't say when it'll be done, but I'd really like to finish it today (+weekend as a deadline)

**Comment by CrusoeDaWolf** [comment]
No problem! Would love to see XashEx running on Linux!

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , could you try to build the mainui using the latest commit?

**Comment by CrusoeDaWolf** [comment]
Ok. Will try in a few minutes.

**Comment by CrusoeDaWolf** [comment]
Do you want me to only build MainUI or do you want me to build other things as well?

**Comment by Sh1ft0x0EF** [comment]
You could try to build everything to check that I didn't break anything in the launcher and for some additional errors from the engine

**Comment by CrusoeDaWolf** [comment]
`[  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
/home/ssardiko/Xash3DEx/launcher/main.cpp:30:32: fatal error: common/commontypes.h: No such file or directory
 #include "common/commontypes.h"
                                ^
compilation terminated.
make[2]: *** [launcher/CMakeFiles/launcher.dir/build.make:63: launcher/CMakeFiles/launcher.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: launcher/CMakeFiles/launcher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
You forgot hlsdk submodule

**Comment by CrusoeDaWolf** [comment]
`[  0%] Building CXX object launcher/CMakeFiles/launcher.dir/main.cpp.o
[  1%] Linking CXX executable ../../bin/cmake/launcher
[  1%] Built target launcher
Scanning dependencies of target menu
[  2%] Building CXX object mainui/CMakeFiles/menu.dir/basemenu.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/menu.dir/menu_advcontrols.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/menu.dir/menu_audio.cpp.o
[  5%] Building CXX object mainui/CMakeFiles/menu.dir/menu_btns.cpp.o
/home/ssardiko/Xash3DEx/mainui/menu_btns.cpp:65:5: error: ‘bute’ does not name a type
     bute rgbBlue;
     ^~~~
make[2]: *** [mainui/CMakeFiles/menu.dir/build.make:135: mainui/CMakeFiles/menu.dir/menu_btns.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: mainui/CMakeFiles/menu.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Sh1ft0x0EF** [comment]
bute 😄

**Comment by Sh1ft0x0EF** [comment]
Could you replace that "bute" with "byte"?

**Comment by Sh1ft0x0EF** [comment]
It it buildable now?

**Comment by CrusoeDaWolf** [comment]
https://pastebin.com/T2TJd3XS

New record reached! 26% xP

**Comment by Sh1ft0x0EF** [comment]
UPD: ripped most of the subsystems out and replaced them with null impl (except for render - this thing is a real mess and so highly tied to the code base so I need a little more time to deal with it). I've compiled it and it successfully crashed. Current libmpg123 is binary incompat with MinGW and I think I will replace it with the original lib or with the whole new module. Also, I made some preparations in external subsystems dll loading so soon the engine should work again.

**Comment by CrusoeDaWolf** [comment]
How about the MAD decoder? Although I would prefer to use the MPG123 lib, MAD is still another possibility. Unsure about binary compatibility with MinGW though

**Comment by Sh1ft0x0EF** [comment]
Dunno
Can't say for sure but maybe I'll implement support for FMOD later and it natively supports mp3 files already (as I know). Also, I'll add the DLL loader from SDLash to support game dlls and to support current AVI decoder which is Win-specific (and most of the other impls are too)

I'm splitting the whole sound module outta the engine and I think that even the sound manager (format loaders) will be split. So in default impl it should be something like original hi-level sound code + low level platform and api specific + sound manager which is responsible for sound files loading. And FMOD should just replace all these things with his impl.

After all these additions it would be possible to use the same engine dll for both client/dedicated server modes with no need for custom dedicated build (but maybe I'll add the possibility to build it as full dedicated server without the full client side part). Can't say how much it would be useful but at least for client mode it will be useful because you'll get the ability to add support for new features and platforms without touching the other unrelated parts + it'll reduce the (re)build time

**Comment by Sh1ft0x0EF** [comment]
Well
MAD looks interesting
I wanna take a look at its sources
Maybe I apply it instead of libmpg123

**Comment by CrusoeDaWolf** [comment]
So, are you planning on using MAD instead of MPG123?

**Comment by Sh1ft0x0EF** [comment]
I need to deal with the subsystems first
But it's possible to use MAD if it's better than MPG123
Soundlib was moved to sound module because it mostly unused by the engine code (Remove the Sound_Init/Shutdown calls and it's absolutely unused)

**Comment by CrusoeDaWolf** [comment]
What is the status of building Xash3DEx on Linux.

**Comment by Sh1ft0x0EF** [comment]
Well
Nothing to say for now
I'll let you know when it'd be buildable

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , could you try to build it? I'm interested in vguiglue module status (but you need to build from the root CMakeLists)
Engine and render are still broken because I've split the renderer code outta the engine and there are lot of unresolved + unfixed glx exports for Linux + render module still has no valid interface for itself
If you're using the cmake-gui you need to select "Default" impl type for MainUI and Engine. Or using the cmdline args:
`-DXASHEX_MAINUI_IMPL_TYPE=Default -DXASHEX_ENGINE_IMPL_TYPE=Default`

**Comment by CrusoeDaWolf** [comment]
build git:(melon-modulesplit) cmake -DXASHEX_MAINUI_IMPL_TYPE=Default -DXASHEX_ENGINE_IMPL_TYPE=Default ../                               
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- XashEx Version: 0.98.1 (Build 3490)
-- Build configuration:
CMake Error at input/CMakeLists.txt:43 (add_subdirectory):
  add_subdirectory given source "Null" which is not an existing directory.


-- Input: Null (MODULE)
CMake Error at mainui/CMakeLists.txt:59 (add_subdirectory):
  add_subdirectory given source "Default" which is not an existing directory.


-- MainUI: Default (MODULE)
CMake Error at network/CMakeLists.txt:43 (add_subdirectory):
  add_subdirectory given source "Null" which is not an existing directory.


-- Network: Null (MODULE)
CMake Error at sound/CMakeLists.txt:44 (add_subdirectory):
  add_subdirectory given source "Null" which is not an existing directory.


-- Sound: Null (MODULE)
CMake Error at system/CMakeLists.txt:43 (add_subdirectory):
  add_subdirectory given source "Null" which is not an existing directory.


-- System: Null (MODULE)
-- Path to VGUI lib: XASHEX_VGUI_LIBRARY_PATH-NOTFOUND
CMake Error at engine/CMakeLists.txt:60 (add_subdirectory):
  add_subdirectory given source "Default" which is not an existing directory.


-- Engine: Default (MODULE)
    - Subsystem Impl: 
-- Launcher: 
    - Single binary: OFF
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XASHEX_VGUI_LIBRARY_PATH
    linked by target "vguiglue" in directory /home/ssardiko/Xash3DEx/vguiglue

-- Configuring incomplete, errors occurred!
See also "/home/ssardiko/Xash3DEx/build/CMakeFiles/CMakeOutput.log".

**Comment by Sh1ft0x0EF** [comment]
Thx
Did it found the system's Null folder?
I probably should fix the case sensitivity for those lines
Can't say why it didn't found the vgui.so for now, that's weird

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , wanna take another try?
I'm planning to spend the weekend finally fixing the modularity and Linux support

**Comment by CrusoeDaWolf** [comment]
Alright. Which branch should I clone?

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , [same](https://github.com/headcrab-garage/Xash3DEx/tree/melon-modulesplit)
You could try to build it initially at its current state to detect the current Linux error list

**Comment by CrusoeDaWolf** [comment]
I get a cmake error right off the bat.

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- XashEx Version: 0.98.1 (Build 3490)
-- Build configuration:
-- Input: null (MODULE)
-- Network: null (MODULE)
-- Sound: null (MODULE)
-- System: null (MODULE)
CMake Warning (dev) at vguiglue/CMakeLists.txt:59:
  Syntax Warning in cmake code at column 17

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at vguiglue/CMakeLists.txt:61:
  Parse error.  Function missing ending ")".  Instead found unterminated
  string with text " ${XASHEX_VGUI_LIBRARY_PATH})

  

  target_link_libraries(${PROJECT_NAME} ${XASHEX_VGUI_LIBRARY_PATH})".


-- Configuring incomplete, errors occurred!
See also "/home/ssardiko/Xash3DEx/build/CMakeFiles/CMakeOutput.log".

**Comment by Sh1ft0x0EF** [comment]
I forgot to complete the OUTPUT_NAME in target properties, fixed
You should have the following build config set up in order to configure and build this thing for now:

> -- Build configuration:
> -- Input: null (MODULE)
> -- MainUI: default (MODULE)
> -- Network: null (MODULE)
> -- Sound: null (MODULE)
> -- System: null (MODULE)
> CMake Warning at CMakeLists.txt:127 (message):
>   VGUI glue module isn't supported by MinGW and will be excluded from build
> 
> 
> -- Engine: default (MODULE)
>     - Subsystem Impl: External (or Null here)
> -- Launcher:
>     - Single binary: OFF
> 

Use the

> -DXASHEX_MAINUI_IMPL_TYPE=Default -DXASHEX_ENGINE_IMPL_TYPE=Default

or CMake GUI app

If vguiglue build would fail (I presume it will) just skip it (comment out the add_subdirectory(vguiglue) inside the root CMakeLists file)

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf 
Alright
It'll be too long to detect all the Linux errors this way
I'll compile it myself using VM
Could you then test it in runtime?

**Comment by CrusoeDaWolf** [comment]
Scanning dependencies of target XashEx-input
[  1%] Building CXX object input/CMakeFiles/XashEx-input.dir/in_int.cpp.o
In file included from /home/ssardiko/Xash3DEx/input/in_int.cpp:30:0:
/home/ssardiko/Xash3DEx/common/in_int.h:32:32: fatal error: common/commontypes.h: No such file or directory
 #include "common/commontypes.h"
                                ^
compilation terminated.
input/CMakeFiles/XashEx-input.dir/build.make:62: recipe for target 'input/CMakeFiles/XashEx-input.dir/in_int.cpp.o' failed
make[2]: *** [input/CMakeFiles/XashEx-input.dir/in_int.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'input/CMakeFiles/XashEx-input.dir/all' failed
make[1]: *** [input/CMakeFiles/XashEx-input.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
Should be fixed now
Edit about module impl types:
> -- Engine: default (MODULE)
> - Subsystem Impl: Null # Must be Null for now

**Comment by CrusoeDaWolf** [comment]
[  5%] Building CXX object input/CMakeFiles/XashEx-input.dir/in_int.cpp.o
In file included from /home/ssardiko/Xash3DEx/input/in_int.cpp:30:0:
/home/ssardiko/Xash3DEx/common/in_int.h:54:3: error: #error "Unsupported platform!"
  #error "Unsupported platform!"
   ^~~~~
input/CMakeFiles/XashEx-input.dir/build.make:62: recipe for target 'input/CMakeFiles/XashEx-input.dir/in_int.cpp.o' failed
make[2]: *** [input/CMakeFiles/XashEx-input.dir/in_int.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'input/CMakeFiles/XashEx-input.dir/all' failed
make[1]: *** [input/CMakeFiles/XashEx-input.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
common/in_int.h:49
`#elif __UNIX__`
->
`#elif __unix__`

**Comment by CrusoeDaWolf** [comment]
Scanning dependencies of target XashEx-input
[  5%] Building CXX object input/CMakeFiles/XashEx-input.dir/in_int.cpp.o
[ 11%] Building CXX object input/CMakeFiles/XashEx-input.dir/null/in_null.cpp.o
[ 17%] Linking CXX shared module ../bin/cmake/in_null.so
[ 17%] Built target XashEx-input
Scanning dependencies of target XashEx-mainui
[ 23%] Building CXX object mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o
/home/ssardiko/Xash3DEx/mainui/udll_int.cpp:17:22: fatal error: basemenu.h: No such file or directory
 #include "basemenu.h"
                      ^
compilation terminated.
mainui/CMakeFiles/XashEx-mainui.dir/build.make:62: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o' failed
make[2]: *** [mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/all' failed
make[1]: *** [mainui/CMakeFiles/XashEx-mainui.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
mainui impl to default

**Comment by CrusoeDaWolf** [comment]
Still the same thing:


[  3%] Built target XashEx-input
[  4%] Building CXX object mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o
/home/ssardiko/Xash3DEx/mainui/udll_int.cpp:17:22: fatal error: basemenu.h: No such file or directory
 #include "basemenu.h"
                      ^
compilation terminated.
mainui/CMakeFiles/XashEx-mainui.dir/build.make:62: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o' failed
make[2]: *** [mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/all' failed
make[1]: *** [mainui/CMakeFiles/XashEx-mainui.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
Try to reconfigure

**Comment by CrusoeDaWolf** [comment]
Scanning dependencies of target XashEx-input
[  1%] Building CXX object input/CMakeFiles/XashEx-input.dir/in_int.cpp.o
[  2%] Building CXX object input/CMakeFiles/XashEx-input.dir/null/in_null.cpp.o
[  3%] Linking CXX shared module ../bin/cmake/in_null.so
[  3%] Built target XashEx-input
Scanning dependencies of target XashEx-mainui
[  4%] Building CXX object mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o
/home/ssardiko/Xash3DEx/mainui/udll_int.cpp:17:22: fatal error: basemenu.h: No such file or directory
 #include "basemenu.h"
                      ^
compilation terminated.
mainui/CMakeFiles/XashEx-mainui.dir/build.make:62: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o' failed
make[2]: *** [mainui/CMakeFiles/XashEx-mainui.dir/udll_int.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'mainui/CMakeFiles/XashEx-mainui.dir/all' failed
make[1]: *** [mainui/CMakeFiles/XashEx-mainui.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
Could you provide the build config info?

**Comment by CrusoeDaWolf** [comment]
As in, commands I am using?

**Comment by Sh1ft0x0EF** [comment]
I mean the output values of engine build config
> -- Build configuration:

**Comment by CrusoeDaWolf** [comment]
Build configuration:
Input: default (MODULE)
MainUI: default (MODULE)
Network: null (MODULE)
Sound: null (MODULE)
Engine: default (MODULE)
    - Subsystem Impl: Default
Launcher: 
    - Single binary: OFF
Configuring done

**Comment by Sh1ft0x0EF** [comment]
Thx
So it's really failing to build the mainui with default impl?

**Comment by CrusoeDaWolf** [comment]
It seems so. I setup everything like you asked:

cmake -DXASHEX_MAINUI_IMPL_TYPE=Default -DXASHEX_ENGINE_IMPL_TYPE=Default ../
Changed __UNIX__ to __unix__
Commented out vguiglue stuff

**Comment by Sh1ft0x0EF** [comment]
btw is vguiglue is even buildable?

**Comment by CrusoeDaWolf** [comment]
When I use cmake to try and build it, it tells me that it can't find the VGUI library:

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Path to VGUI lib: XASHEX_VGUI_LIBRARY_PATH-NOTFOUND
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XASHEX_VGUI_LIBRARY_PATH
    linked by target "XashEx-vguiglue" in directory /home/ssardiko/Xash3DEx/vguiglue

-- Configuring incomplete, errors occurred!
See also "/home/ssardiko/Xash3DEx/vguiglue/build/CMakeFiles/CMakeOutput.log".

**Comment by Sh1ft0x0EF** [comment]
Probably because it's not oriented on non-root build

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf 
Could you skip the mainui build for now then?

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf 
Ok
I will be working on this thing for the next week
Will you be able to make test builds once per (1-)2 days during this time?
Thanks for the help, I really appreciate that

**Comment by CrusoeDaWolf** [comment]
I will try! Hope to see this running on Linux soon!

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf , which version of CMake you have installed?

**Comment by CrusoeDaWolf** [comment]
3.8.0

**Comment by CrusoeDaWolf** [comment]
This is what I get now after cloning and updating everything:

Scanning dependencies of target XashEx-dedicated
[  6%] Building CXX object dedicated/CMakeFiles/XashEx-dedicated.dir/main.cpp.o
[ 12%] Linking CXX executable ../bin/cmake/xashds
/usr/bin/ld: i386:x86-64 architecture of input file `CMakeFiles/XashEx-dedicated.dir/main.cpp.o' is incompatible with i386 output
/usr/bin/ld: CMakeFiles/XashEx-dedicated.dir/main.cpp.o: file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
dedicated/CMakeFiles/XashEx-dedicated.dir/build.make:94: recipe for target 'bin/cmake/xashds' failed
make[2]: *** [bin/cmake/xashds] Error 1
CMakeFiles/Makefile2:85: recipe for target 'dedicated/CMakeFiles/XashEx-dedicated.dir/all' failed
make[1]: *** [dedicated/CMakeFiles/XashEx-dedicated.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf 
Oh, I got it
It's because of Linux case-sensitivity (again)
Well, impl type is in higher case
It goes to include_directories in that case
So it tries to search for "Default" not "default" folder and such
Should be fixed now for mainui and engine modules

**Comment by CrusoeDaWolf** [comment]
I still get the same thing after deleting CMakeCache.txt:

[  6%] Linking CXX executable ../bin/cmake/xashds
/usr/bin/ld: i386:x86-64 architecture of input file `CMakeFiles/XashEx-dedicated.dir/main.cpp.o' is incompatible with i386 output
/usr/bin/ld: CMakeFiles/XashEx-dedicated.dir/main.cpp.o: file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
dedicated/CMakeFiles/XashEx-dedicated.dir/build.make:94: recipe for target 'bin/cmake/xashds' failed
make[2]: *** [bin/cmake/xashds] Error 1
CMakeFiles/Makefile2:85: recipe for target 'dedicated/CMakeFiles/XashEx-dedicated.dir/all' failed
make[1]: *** [dedicated/CMakeFiles/XashEx-dedicated.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sh1ft0x0EF** [comment]
Try to delete the `CMakeFiles/XashEx-dedicated.dir/main.cpp.o'
Check project's cmake settings, it looks like the compiler is x64 (but even that it should compile x32 code for the project) and linker is x32

**Comment by Sh1ft0x0EF** [comment]
Buildable by CMake (at least partially; still Win-only)
